# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b0c61d0bc220e7934acb3ec799b9df16482e723bdc7e5a26d9ab246afe32091071efd412c8668c19be68bf7e504a8ca77a71cae94cebdde76663b0ce49eb61f8

test:
  secret_key_base: 55d43a66e2ab8884d06323919af49e2fe4284eab064ca551b2f20461c5f06c73962085539af48fa81bd74a0464e6343c26ade301f53fd1b1127960a6a44e1763

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
